<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>yolo_vision</name>
  <version>0.0.1</version>
  <description>perform yolo based detection</description>
  <maintainer email="parthasrivachu@gmail.com">pvsp</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>yolo_detect_interfaces</depend>

  <!-- System deps -->
  <exec_depend>opencv</exec_depend>
  <exec_depend>onnxruntime</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
